name: furtherance
description: Track your time without being tracked.

publish_to: 'none'

version: 1.0.6+7

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  stop_watch_timer: ^1.5.0
  sqflite: ^2.0.3
  path_provider: ^2.0.11
  intl: ^0.17.0
  path: ^1.8.1
  grouped_list: ^5.1.2
  tuple: ^2.0.0
  swipe_to: ^1.0.2
  shared_preferences: ^2.0.15
  flutter_spinbox: ^0.9.0
  flutter_local_notifications: ^9.9.1
  flutter_native_splash: ^2.2.8
  flutter_native_timezone: ^2.0.0
  auto_size_text: ^3.0.0
  timezone: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - assets/splash.png